	\context ChordNames
		\chords {
		\set chordChanges = ##t

		% intro
		g2. g2. d2. b2.:7
		e2.:m e2.:m b2.:m b2.:m 
		c4. a4.:m7 c2.
		g2. g2.
		f2. c2. a2.:m7 d2.
		d2.:7

		% hoy que traemos...
		g2. g2. d2. b2.:7
		e2.:m e2.:m b2.:m b2.:m 
		c4. a4.:m7 c2.
		g2. g2.
		f2. c2. a2.:m7 d2.
		d2.:7

		% hoy que traemos...
		g2. g2. d2. b2.:7
		e2.:m e2.:m b2.:m b2.:m 
		c4. a4.:m7 c2.
		g2. g2.
		f2. c2. a2.:m7 d2.
		d2.

		}
