\context ChordNames \chords {
	% intro
	\break
	\skip 2.*17

	% Hoy que traemos...
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\skip 2.*1

	% Hoy que traemos...
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\skip 2.*1

	% Te rogamos, padre...
	\break
	\skip 2.*2
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4

	% Hoy que traemos...
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\skip 2.*1

	% Hoy que traemos...
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\skip 2.*1

	% Te rogamos, padre...
	\break
	\skip 2.*2
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4

	% Hoy que traemos...
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\skip 2.*1

	% Hoy que traemos...
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\break
	\skip 2.*4
	\skip 2.*1
}
